name: CI
on: [push]
env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: install libudev
        run: sudo apt-get install libudev-dev
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose

  build-wasm:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: install libudev
        run: sudo apt-get install libudev-dev
      - name: add wasm target
        run: rustup target add wasm32-unknown-unknown
#      - name: install wasm-pack
#        run: cargo install wasm-pack
      - name: install wasm-bindgen
        run: cargo install wasm-bindgen-cli
      - name: build wasm
        run: cargo build --release --target wasm32-unknown-unknown --features quicksilver/web-sys
      - name: wasm bindgen
        run: wasm-bindgen --no-typescript --target web --out-name wasm --out-dir target/distribution target/wasm32-unknown-unknown/release/quicksilver-web.wasm
      - name: copy static files
        run: cp index.html target/distribution
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: target/distribution # The folder the action should deploy.
